### ISSUE TITLE
kirby install:kit is not working

### ISSUE THREAD

**Issue by mi-skam** [getkirby/cli#43] opened 2023-03-08 11:57 UTC
Using kirby cli **1.1.1*, I cannot install any kits like _plainkit_. The installation folder is empty afterwards.

[![asciicast](https://asciinema.org/a/kmGaHPmrqaoIBciUj3HGPUmgn.svg)](https://asciinema.org/a/kmGaHPmrqaoIBciUj3HGPUmgn)

**Comment by plagasul** [comment] 2023-03-15 09:59
I am getting the same error on Linux mint 21 cinnamon, composer 2.2.6 

The folder is created, but empty.

Other commands such as `kirby make:command` work.

Let me know if you want me to troubleshoot.

Thanks

**Comment by plagasul** [comment] 2023-03-15 14:13
It seems the error comes from [line 43](https://github.com/getkirby/cli/blob/0e8074b0e6081c9e1a9f31090733b058db15be06/commands/unzip.php#L43) of the 'unzip' command, where it says:

`exec('mv ' . $to . '/*/{.[!.],}* ' . $to . '/');`

I find two similar cases online where the issue is that `*` should go outside of the quotes, see [here](https://unix.stackexchange.com/questions/77007/mv-cannot-stat-no-such-file-or-directory-in-shell-script) and [here](https://stackoverflow.com/questions/34254164/getting-an-error-cp-cannot-stat-when-trying-to-copy-files-from-one-folder-to-an).

Perhaps that helps.

Perhaps also relevant to say that I am using zsh

@mi-skam What OS, composer version and terminal are you using?

**Comment by bastianallgeier** [comment] 2023-04-25 06:58
I'm closing this in favour of https://github.com/getkirby/cli/issues/44

**Closed by bastianallgeier** 2023-04-25 06:58 UTC
